name: odac_flutter_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# 버전관리 ( Version name, Version Code )
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2 # iOS system
  kakao_flutter_sdk_user: ^1.2.1 # kakao login
  package_info_plus: ^3.0.3
  equatable: ^2.0.5
  serializable: ^1.0.0
  either_dart: ^0.3.0
  get_it: ^7.2.0
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.17
  change_app_package_name: ^1.0.0

flutter:
  generate: true
  uses-material-design: true

fonts:
  - family: Sc_Dream
    fonts:
      - asset: assets/fonts/sc_dream1.otf
        weight: 100
      - asset: assets/fonts/sc_dream2.otf
        weight: 200
      - asset: assets/fonts/sc_dream3.otf
        weight: 300
      - asset: assets/fonts/sc_dream4.otf
        weight: 400
      - asset: assets/fonts/sc_dream5.otf
        weight: 500
      - asset: assets/fonts/sc_dream6.otf
        weight: 600
      - asset: assets/fonts/sc_dream7.otf
        weight: 700
      - asset: assets/fonts/sc_dream8.otf
        weight: 800
      - asset: assets/fonts/sc_dream9.otf
        weight: 900

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  image: assets/imgs/logo.png
  image_dark: assets/imgs/logo.png

  # Android 12 이상 버전에서 적용
  android_12:
    image: assets/imgs/logo.png
    image_dark: assets/imgs/logo.png
    color: "#FFFFFF"
    color_dark: "#FFFFFF"
