name: odac_flutter_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# 버전관리 ( Version name, Version Code )
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2 # iOS system
  animated_text_kit: ^4.2.2
  flutter_hooks: ^0.18.6
  riverpod: ^2.3.2
  flutter_svg: ^2.0.4
  hooks_riverpod: ^2.3.2
  table_calendar: ^3.0.8
  get_it: ^7.6.0
  http: ^0.13.6
  shared_preferences: ^2.1.1
  firebase_core: ^2.13.0
  google_sign_in: ^6.1.0
  json_annotation: ^4.8.1
  flutter_native_timezone: ^2.0.0
  firebase_auth: ^4.6.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.17
  json_serializable: ^6.6.2
  build_runner: ^2.3.3

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/fonts/

  fonts:
    - family: AppleSDGothicNeoa
      fonts:
        - asset: assets/fonts/AppleSDGothicNeo-T.ttf
          weight: 100
        - asset: assets/fonts/AppleSDGothicNeo-UL.ttf
          weight: 200
        - asset: assets/fonts/AppleSDGothicNeo-L.ttf
          weight: 300
        - asset: assets/fonts/AppleSDGothicNeo-R.ttf
          weight: 400
        - asset: assets/fonts/AppleSDGothicNeo-M.ttf
          weight: 500
        - asset: assets/fonts/AppleSDGothicNeo-SB.ttf
          weight: 600
        - asset: assets/fonts/AppleSDGothicNeo-B.ttf
          weight: 700
        - asset: assets/fonts/AppleSDGothicNeo-EB.ttf
          weight: 800
        - asset: assets/fonts/AppleSDGothicNeo-H.ttf
          weight: 900

flutter_native_splash:
  image: assets/imgs/logo.png
  image_dark: assets/imgs/logo.png
  color: "#FFFFFF"
  color_dark: "#FFFFFF"

  # Android 12 이상 버전에서 적용
  android_12:
    image: assets/imgs/logo.png
    image_dark: assets/imgs/logo.png
    color: "#FFFFFF"
    color_dark: "#FFFFFF"