// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqXf-zq0YW9YXtaVxC6CQCxqsrfoqu6vY',
    appId: '1:15204988302:android:5d835fc0704eca23e120df',
    messagingSenderId: '15204988302',
    projectId: 'ody-app-dev',
    storageBucket: 'ody-app-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4vHrTyTjzzLEdD5_FZjKqEVdGjGpvgCM',
    appId: '1:15204988302:ios:8bb0198d44e614c9e120df',
    messagingSenderId: '15204988302',
    projectId: 'ody-app-dev',
    storageBucket: 'ody-app-dev.appspot.com',
    androidClientId: '15204988302-86r6aeij0c16bilfo5inv2h2fqgkgam1.apps.googleusercontent.com',
    iosClientId: '15204988302-f47hudjuqr6vj3cajbi1ekk912mv0i5c.apps.googleusercontent.com',
    iosBundleId: 'com.orot.ody.dev',
  );
}
