// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYno5Xp8kHPC3cbP0YjimScUMa3okM1Go',
    appId: '1:1043075265104:android:41b6726dea064ea27c9755',
    messagingSenderId: '1043075265104',
    projectId: 'orotcode-ody',
    storageBucket: 'orotcode-ody.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWinpwWkKIRid2ARYOcRrpyv0gekdIL-A',
    appId: '1:1043075265104:ios:5f201c12607adeb17c9755',
    messagingSenderId: '1043075265104',
    projectId: 'orotcode-ody',
    storageBucket: 'orotcode-ody.appspot.com',
    androidClientId: '1043075265104-1t6ac85tt4lruc1di83asbujr4bl07eo.apps.googleusercontent.com',
    iosClientId: '1043075265104-65irrc3i3gnif14d69fd6el6avsso6km.apps.googleusercontent.com',
    iosBundleId: 'com.orot.ody',
  );
}
