// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUnmxMWLjfzRFVvHigr4y_vDvV0oEdXsc',
    appId: '1:739051866939:android:bea59afbd28c3aac1d851e',
    messagingSenderId: '739051866939',
    projectId: 'orotcode-ody-dev',
    storageBucket: 'orotcode-ody-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_tLq2Zrpy59N3pTpkDhONvGi5NTBGY0w',
    appId: '1:739051866939:ios:f311bbe2eecda8881d851e',
    messagingSenderId: '739051866939',
    projectId: 'orotcode-ody-dev',
    storageBucket: 'orotcode-ody-dev.appspot.com',
    androidClientId: '739051866939-vvhba8lbfu8vnvj0egp3ld6ijov2apcq.apps.googleusercontent.com',
    iosClientId: '739051866939-7ii7c6od0j78mu7idigtm1e2tpjqlstg.apps.googleusercontent.com',
    iosBundleId: 'com.orot.ody.dev',
  );
}
